server:
  port: 8082
  servlet:
    context-path: '/ead-course/' # path da rota do gateway

spring:
  application:
    name: ead-course-service
  #  configuracao do banco
  datasource:
    url: jdbc:postgresql://localhost:5432/ead-course-async
    username: postgres
    password: 1234567

  jpa:
    hibernate:
      ddl-auto: update  # cria as tabelas automaticamente no banco
      dialect: org.hibernate.dialect.PostgreSQLDialect  # dialeto do postgres
      jdbc:
        lob.non-contextual-creation: true # evita logs de erro (devido consultas do hibernate a metadados do banco)
    properties:
      hibernate:
        show_sql: true # mostra as consultas no log

# configuração de logs
logging:
  level:
    com.ead: TRACE
    root: INFO
    org.springframework.web: DEBUG
    org.hibernate: INFO

ead:
  api:
    url:
      authuser: 'http://ead-authuser-service/ead-authuser' # nome do servico de authuser e o seu context path

eureka:
  client:
    serviceUrl:
      defaultZone: 'http://localhost:8761/eureka' # endereco onde o eureka esta disponivel

  instance:
    hostname: localhost # para se registrar utilizando host
